### ISSUE TITLE
取消请求和请求超时为什么不走拦截器呢？

### ISSUE THREAD

**Issue by WangZhenHao** [yinchengnuo/uni_request#1]
建议参考aixos功能，取消请求和请求超时也要走拦截器

**Comment by yinchengnuo** [comment]
会被请求拦截器拦截但是不会被响应拦截器拦截，因为服务器没响应。但是这两种情况会触发 onerror 发自我的华为手机-------- 原始邮件 --------发件人： WangZhenHao <notifications@github.com>日期： 2020年7月31日周五 16:38收件人： yinchengnuo/uni_request <uni_request@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [yinchengnuo/uni_request] 取消请求和请求超时为什么不走拦截器呢？ (#1)

建议参考aixos功能，取消请求和请求超时也要走拦截器

**Comment by yinchengnuo** [comment]
> 建议参考aixos功能，取消请求和请求超时也要走拦截器

刚看到了axios源码，明白你的意思了，等会加上拦截器 use 的第二个参数

**Comment by yinchengnuo** [comment]
use 增加第二个参数过于麻烦。现有的 API 亦可以满足需求。
