### ISSUE TITLE
代码求解

### ISSUE THREAD

**Issue by shmilyxwx** [yinchengnuo/uni_request#3]
interceptors: [],
use(fun, err) { this.interceptors.push(fun) },
拦截其中的两行代码都没有使用到额,我不太清楚你写这两行

**Comment by yinchengnuo** [comment]
> interceptors: [],
> use(fun, err) { this.interceptors.push(fun) },
> 拦截其中的两行代码都没有使用到额,我不太清楚你写这两行

已删除 err
